version: "3"
services:
    db:
        image: postgres:13.0-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=123qwe
            - POSTGRES_DB=movies_database
            - PGDATA=/var/lib/postgresql/data
        networks:
            - local-dev
        ports:
            - "5432:5432"
    elasticsearch:
        image: elasticsearch:7.17.9
        environment:
            - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - local-dev
    redis:
        restart: on-failure
        image: redis:7.0.8-alpine
        command: redis-server
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf
        networks:
            - local-dev

volumes:
    elasticsearch_data:
    redis-data:
    redis-conf:
    pgdata:

networks:
  local-dev:
    driver: bridge
