version: "3"
services:
    db:
        image: postgres:13.0-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=123qwe
            - POSTGRES_DB=movies_database
            - PGDATA=/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - .env
        networks:
            - local-dev
    elasticsearch:
        image: elasticsearch:7.17.9
        environment:
            - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"
            - "USE_SSL=false"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        env_file:
            - .env
        networks:
            - local-dev
    etl:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - elasticsearch
        env_file:
            - .env
        networks:
            - local-dev


volumes:
    elasticsearch_data:
    pgdata:

networks:
  local-dev:
    driver: bridge
